### PR TITLE
Fix/validate long numbers

### PR DESCRIPTION
**Pull request by janjelinek**
This is resolving #4 and also this change is BC break as I mentioned. 
I also added some basic `package.json` and changed some versions of packages used for running test for help others run tests without investigation which version of elm-test is necessary :)

This PR containts several commits. First I added tests and then I changed original implementation to pass all test. And after I have idea about change some logic so I created new implementation of validation and this is in separated commit. So If you don't like it I can remove this commit easily.

I tested new implementation vs original and seems to be faster. You can check it here:
https://plnkr.co/edit/CWlOL6NUpsSItZCRNTcb?p=preview 

Because is late it can contains some nonsense, typos or any strange things, so if you find anything, I'll fix it ;)

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Very nice! Thanks a lot :) I'll maybe change from 4 spaces to two, but everything else seems pretty good.

**Comment by janjelinek** [comment]
I'm using https://github.com/avh4/elm-format onSave but as you wish, I can reformat it if you want. Just tell me your final decision `Just "change from 4 spaces to two"` or `Nothing`?

**Comment by janjelinek** [comment]
Indentation changed just for any case.

**Comment by janjelinek** [comment]
ping @ersocon 
We would like to update this library in our project. When do you plan prepare new release?

**Pull request merged**
